import './user.spec';
import './socialLoginSpec';
import './profile.spec';
import './login.spec';
import './article.spec';
import './resetpassword.spec';
import './updateVerifiedStatusHelper.spec';
import './category.spec';
import './rating.spec';
