export default [
  {
    title: 'This is the first article',
    description: 'This is the description of this article',
    body: 'This is the body',
    slug: 'this-is-the-first-article-111111111',
    taglist: [],
    images: ['https://images.pexels.com/photos/934718/pexels-photo-934718.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=208&w=275'],
    userId: 1,
    categoryId: 1,
  },
  {
    title: 'This is the second article',
    description: 'This is the description of this article',
    body: 'This is the body',
    slug: 'this-is-the-second-article-222222222',
    taglist: [],
    images: ['https://images.pexels.com/photos/1257105/pexels-photo-1257105.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=208&w=275'],
    userId: 1,
    categoryId: 1,
  },
  {
    title: 'This is the third article',
    description: 'This is the description of this article',
    body: 'This is the body',
    slug: 'this-is-the-third-article-333333333',
    taglist: [],
    images: ['https://images.pexels.com/photos/1094072/pexels-photo-1094072.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=208&w=275'],
    userId: 1,
    categoryId: 1,
  },
  {
    title: 'This is the fourth article',
    description: 'This is the description of this article',
    body: 'This is the body',
    slug: 'this-is-the-fourth-article-444444444',
    taglist: [],
    images: ['https://images.pexels.com/photos/316465/pexels-photo-316465.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=208&w=275'],
    userId: 1,
    categoryId: 1,
  },
  {
    title: 'This is the fifth article',
    description: 'This is the description of this article',
    body: 'This is the body',
    slug: 'this-is-the-fifth-article-555555555',
    taglist: [],
    images: ['https://images.pexels.com/photos/886521/pexels-photo-886521.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=208&w=275'],
    userId: 1,
    categoryId: 1,
  },
  {
    title: 'This is the sixth article',
    description: 'This is the description of this article',
    body: 'This is the body',
    slug: 'this-is-the-sixth-article-666666666',
    taglist: [],
    images: [],
    userId: 1,
    categoryId: 1,
  },
  {
    title: 'This is the seventh article',
    description: 'This is the description of this article',
    body: 'This is the body',
    slug: 'this-is-the-seventh-article-777777777',
    taglist: [],
    images: [],
    userId: 1,
    categoryId: 1,
  },
  {
    title: 'This is the eight article',
    description: 'This is the description of this article',
    body: 'This is the body',
    slug: 'this-is-the-eight-article-888888888',
    taglist: [],
    images: [],
    userId: 1,
    categoryId: 1,
  },
  {
    title: 'This is the ninth article',
    description: 'This is the description of this article',
    body: 'This is the body',
    slug: 'this-is-the-ninth-article-999999999',
    taglist: [],
    images: [],
    userId: 1,
    categoryId: 1,
  },
  {
    title: 'This is the tenth article',
    description: 'This is the description of this article',
    body: 'This is the body',
    slug: 'this-is-the-tenth-article-101010101',
    taglist: [],
    images: [],
    userId: 1,
    categoryId: 1,
  }
];
